
set_property PACKAGE_PIN AA19 [get_ports IIC_0_0_sda_io]
set_property PACKAGE_PIN AB16 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN AB19 [get_ports {data[0]}]
set_property PACKAGE_PIN AB21 [get_ports {data[2]}]
set_property PACKAGE_PIN AA21 [get_ports {data[1]}]
set_property PACKAGE_PIN AA22 [get_ports {data[3]}]
set_property PACKAGE_PIN AB22 [get_ports {data[4]}]
set_property PACKAGE_PIN Y20 [get_ports {data[5]}]
set_property PACKAGE_PIN Y21 [get_ports {data[6]}]
set_property PACKAGE_PIN V22 [get_ports {data[7]}]
set_property PACKAGE_PIN W22 [get_ports pclk]
set_property PACKAGE_PIN AA16 [get_ports vsync]
set_property PACKAGE_PIN Y19 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN AB20 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN U22 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports href]
set_property IOSTANDARD LVCMOS33 [get_ports pclk]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PULLUP true [get_ports IIC_0_0_sda_io]
set_property PULLUP true [get_ports IIC_0_0_scl_io]
